package com.spordee.user.enums.sports.soccer;

public enum SoccerPositions {

    GOALKEEPER, SWEEPER, CENTRE_DEFENCE, RIGHT_BACK, LEFT_BACK, CENTRE_DEFENSIVE_MIDFIELDER, CENTRE_ATTACKING_MIDFIELDER, RIGHT_MIDFIELD, LEFT_MIDFIELD, STRIKER, LEFT_WING, RIGHT_WING
}
