spring:
  data:
    mongodb:
      uri: mongodb+srv://xenia:xenia@xenia.0r1mx1j.mongodb.net/phaseTwoDatabase2?retryWrites=true&w=majority&ssl=true
      auto-index-creation: true
  application:
    name: XENIA-SERVICE

server:
  port: 8999