spring:
  data:
    mongodb:
      uri: mongodb+srv://xenia:xenia@xenia.0r1mx1j.mongodb.net/phaseTwoDatabase3?retryWrites=true&w=majority&ssl=true
      auto-index-creation: true
#      host: localhost
#      port: 27017
#      database: SpordOnboarding
  application:
    name: XENIA-SERVICE

server:
  port: 8999

jwt: # Store token in a Volute
  secret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
  tokenDecryptCode: kfsdSDFsdfmflks32FSDskfdskfsdSDFsdfmflks32FSDskfdskfsdSDFsdfmflks32FSDskfdskfsdSDFsdfmflks32FSDskfds

api:
  class:
    header: /user/onboarding
    method: /v1/save
    class-update-user: /user/update
    methods:
      personal_details: /personalDetails
      specs: /update/specs
      skills: /update/skills
      achievements: /update/achievements
