package com.spordee.user.dto;

import com.spordee.user.dto.objects.UserImagesDto;
import com.spordee.user.dto.objects.UserSportsDto;
import com.spordee.user.enums.*;
import lombok.*;

import java.util.List;
import java.util.Set;

@AllArgsConstructor
@NoArgsConstructor
@Setter
@Getter
@ToString
@Builder
public class InitialUserSaveRequestDto {
    private String id;
    private String userName;
    private String firstName;
    private RegistrationType registrationType;
    private String lastName;
    private SportsGender sportsGender;
    private ClubGender clubGender;
    private String countryCode;
    private String country;
    private String city;
    private String birthCountry;
    private String birthCity;
    private boolean isPremium;// Generated By the BackEnd
    private UserStatus userStatus; // Enum
    private boolean openJob;
    private boolean isVerified;
    private long birthDay;
    private long createdDate;
    private long updatedDate;
    private String weight;
    private String height;
    private List<UserImagesDto> userImagesDtos;
    private UserSportsDto userSportsDtos;
    private String favPlayer;
    private String favClubTeam;
    private String favAllTimePlayer;
    private String favNationalTeam;
    private Sport favSport;
    private Set<Sport> secondaryFavSports;

    private String userEmail;

}
